### ISSUE TITLE
giving error cannot locate cassandra.yaml

### ISSUE THREAD

**Issue by cw-deenbandhu** [feldoh/extractSSTableData#1]
running for cassandra2.1.12  

I am getting this error

ERROR config.DatabaseDescriptor: Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Cannot locate cassandra.yaml
    at org.apache.cassandra.config.DatabaseDescriptor.getStorageConfigURL(DatabaseDescriptor.java:113)
    at org.apache.cassandra.config.DatabaseDescriptor.loadYaml(DatabaseDescriptor.java:130)
    at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:122)
    at net.imagini.cassandra.DumpSSTables.SSTableExportMapper.main(SSTableExportMapper.java:295)
Cannot locate cassandra.yaml

**Comment by feldoh** [comment]
This was written for Cassandra 1.x it may not work for 2.x the schema's being very different now but there are now better tools supported by Cassandra for the same purpose anyway such as https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsSSTable2JsonNew.html if you want raw SSTable dumping or https://github.com/brianmhess/cassandra-loader for a table based dumper, the cassandra-spark-connector or even org.apache.cassandra.hadoop.cql3.CqlInputFormat. This was written because Hadoop could not read from Cassandra without crippling it but this is no longer true. In Cassandra 2.X sstable streaming has become very efficient and many options exist using that strategy so that would be my recommendation. Especially given you effectively need to run this on every node and merge the results.
